spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-batch
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always